### ISSUE TITLE
review

### ISSUE THREAD

**Issue by ale-strada** [bautistaJuan/desafio-m3#1]
Hola @bautistaJuan como va? Felicitaciones!! Te quedo muy prolija la web y se adapta muy bien a los cambios de tamaño. Solo tengo una obsevacion para hacer, tu foto en version grande esta un poco achatada. es xq al momento de poner el atributo height en el css le pusiste el nro y te falto el "px" x eso no te toma la altura de la foto.  Lo demas esta muy bien 🚀💪. Saludos!

**Comment by bautistaJuan** [comment]
Hola @ale-strada !! Muchas gracias!!! 
No me había dado cuenta :/ ya esta solucionado gracias por la observación 🤝 
Saludos !
